version: '3'

services:
  redis:
    image: docker.io/redis
    container_name: "redis-db"
    command: "redis-server"

  backend:
    build: .
    container_name: "backend-api"
    command: "app -db redis-db:6379"
    depends_on:
      - redis

  nginx:
    image: docker.io/nginx
    volumes:
      - "./website:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports: "8080:8080"   
    depends_on:
      - backend

networks:
  defualt:
    name: internal
